import type { MongoAction } from "@/types/mongo";

export const ACTION_VERB_MAP: Record<MongoAction, string[]> = {
  insertOne: [
    "agregar",
    "agrega",
    "registrar",
    "registra",
    "cargar",
    "carga",
    "anotar",
    "crear",
    "crea",
    "guardar",
    "guarda",
    "insertar",
    "inserta",
    "insert",
    "add",
    "create",
    "save"
  ],
  updateMany: ["actualizar", "actualiza", "modificar", "modifica", "editar", "edita", "cambiar", "cambia", "update", "edit", "change"],
  deleteMany: ["borrar", "borra", "eliminar", "elimina", "sacar", "quitar", "quita", "delete", "remove"],
  count: ["contar", "cuantos", "cuantas", "total", "count", "how many"],
  find: [
    "mostrar",
    "mostrame",
    "ver",
    "listar",
    "lista",
    "consultar",
    "consulta",
    "buscar",
    "busca",
    "trae",
    "traeme",
    "dame",
    "damelo",
    "show",
    "find",
    "list",
    "query"
  ]
};

export const COLLECTION_CANDIDATES = [
  "transactions",
  "transacciones",
  "movimientos",
  "gastos",
  "users",
  "usuarios",
  "clientes",
  "products",
  "productos",
  "audit_logs",
  "auditlogs",
  "logs",
  "plans",
  "planes",
  "entries",
  "entradas"
];

export const COLLECTION_ALIAS: Record<string, string> = {
  transacciones: "transactions",
  movimientos: "transactions",
  gastos: "transactions",
  usuarios: "users",
  productos: "products",
  auditlogs: "audit_logs",
  logs: "audit_logs",
  planes: "plans",
  entradas: "entries"
};

export const COLLECTION_BLOCKLIST = [
  "agrega",
  "agregar",
  "registra",
  "registrar",
  "carga",
  "cargar",
  "mostrar",
  "mostrame",
  "show",
  "find",
  "list",
  "query",
  "delete",
  "remove",
  "insert",
  "add",
  "update",
  "count",
  "where",
  "when",
  "with",
  "contar",
  "cuantos",
  "cuantas",
  "hoy",
  "ayer",
  "manana",
  "pasado",
  "anteayer",
  "semana",
  "mes",
  "ano",
  "dia",
  "dias",
  "enero",
  "febrero",
  "marzo",
  "abril",
  "mayo",
  "junio",
  "julio",
  "agosto",
  "septiembre",
  "setiembre",
  "octubre",
  "noviembre",
  "diciembre",
  "lunes",
  "martes",
  "miercoles",
  "jueves",
  "viernes",
  "sabado",
  "domingo",
  "el",
  "la",
  "los",
  "las",
  "un",
  "una",
  "en",
  "de",
  "del",
  "con",
  "in",
  "general",
  "consulta",
  "y",
  "o"
];

export const NORMALIZE_FILLER_WORDS = [
  "por favor",
  "porfa",
  "che",
  "ok",
  "dale",
  "me podes",
  "me podrias",
  "podrias",
  "podria"
];

export const NORMALIZE_NUM_WORD_MAP: Record<string, string> = {
  uno: "1",
  una: "1",
  dos: "2",
  tres: "3",
  cuatro: "4",
  cinco: "5",
  seis: "6",
  siete: "7",
  ocho: "8",
  nueve: "9",
  diez: "10",
  veinte: "20",
  treinta: "30",
  cuarenta: "40",
  cincuenta: "50",
  cien: "100",
  quinientos: "500",
  mil: "1000"
};

export const MONTH_NAME_TO_INDEX: Record<string, number> = {
  enero: 0,
  febrero: 1,
  marzo: 2,
  abril: 3,
  mayo: 4,
  junio: 5,
  julio: 6,
  agosto: 7,
  septiembre: 8,
  setiembre: 8,
  octubre: 9,
  noviembre: 10,
  diciembre: 11,
  jan: 0,
  january: 0,
  feb: 1,
  february: 1,
  mar: 2,
  march: 2,
  apr: 3,
  april: 3,
  may: 4,
  jun: 5,
  june: 5,
  jul: 6,
  july: 6,
  aug: 7,
  august: 7,
  sep: 8,
  sept: 8,
  september: 8,
  oct: 9,
  october: 9,
  nov: 10,
  november: 10,
  dec: 11,
  december: 11
};

export const WEEKDAY_NAME_TO_INDEX: Record<string, number> = {
  lunes: 1,
  martes: 2,
  miercoles: 3,
  jueves: 4,
  viernes: 5,
  sabado: 6,
  domingo: 0,
  monday: 1,
  tuesday: 2,
  wednesday: 3,
  thursday: 4,
  friday: 5,
  saturday: 6,
  sunday: 0
};
